# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: DisplayFusion.DisplayFusion.Beta
PackageVersion: 11.0.5
PackageLocale: en-US
Publisher: Binary Fortress Software
PublisherUrl: https://www.binaryfortress.com/
Author: Binary Fortress Software
PackageName: DisplayFusion
License: Proprietary
LicenseUrl: https://www.displayfusion.com/license
Copyright: Copyright © 2007-2024 Binary Fortress Software
ShortDescription: DisplayFusion will make managing your multiple monitors easy!
Description: Multiple Monitors Made Easy! DisplayFusion will make your multi-monitor life much easier! With powerful features like Multi-Monitor Taskbars, TitleBar Buttons and fully customizable HotKeys, DisplayFusion will make managing your multiple monitors easy.
Moniker: displayfusion-beta
Tags:
- control
- hotkey
- lockscreen
- management
- monitor
- multi-monitor
- remote
- snapping
- taskbar
- tweaks
- wallpaper
- window
- windows
ReleaseNotesUrl: https://www.displayfusion.com/ChangeLog/Beta/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
